name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [11, 17, 25]
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.12.0.1530
          bb: latest

      - name: Run tests
        run: bb test
